version: '2.1'
services:
  db:
    container_name: sopmdb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sopmdb'
      MYSQL_USER: 'sopm'
      MYSQL_PASSWORD: 'sopm'
      MYSQL_ROOT_PASSWORD: 'sopm'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - sopmdb:/var/lib/mysql
volumes:
  sopmdb: